const products = [
  {
    title: 'Featured Products',
    items: [
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
    ],
  },
  {
    title: 'Best Sellers',
    items: [
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
    ],
  },
  {
    title: 'New Arrivals',
    items: [
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
    ],
  },
  {
    title: 'Top Rated Products',
    items: [
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
    ],
  },
  {
    title: 'Special Offers',
    items: [
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
      {
        title: 'TMA-2 HD Wireless Speaker',
        price: '$199.99',
        image: 'https://picsum.photos/100/250',
        rating: 4.5,
        reviews: 32,
      },
    ],
  },
]

export default products
